package com.bnpparibas.dsibddf.fis.pvi.domain.model;

public enum TaxOutcomeState {
    NON_IMPOSABLE_MOINS_VALUE,
    NON_IMPOSABLE_SEUIL_PRIX_VENTE,
    NON_IMPOSABLE_RESIDENCE_PRINCIPALE,
    NON_IMPOSABLE_EXONERATION_DUREE,
    IMPOSABLE_PS_SEULEMENT,
    IMPOSABLE_IR_PS,
    IMPOSABLE_IR_PS_SURTAXE
}
